name = "gospel-reach-me-worker"
main = "src/index.js"
compatibility_date = "2025-05-22"

# Durable Object Binding
[[durable_objects.bindings]]
name = "GLOBAL_COUNTER_DO"
class_name = "GlobalCounter"

# Durable Object Migrations
[[migrations]]
tag = "v1"
new_classes = ["GlobalCounter"]

# Environment Variables
[vars]
# Add any public environment variables here

# Secrets
# Use `wrangler secret put TURNSTILE_SECRET_KEY` to set this
# TURNSTILE_SECRET_KEY